### ISSUE TITLE
Reverse DNS zone handling incorrect

### ISSUE THREAD

**Issue by domcleal** [theforeman/smart_proxy_dns_route53#1] opened 2015-07-10 13:18 UTC
The rDNS zone handling is a bit broken as far as I can tell.  It's searching for zones like it would with forward DNS, so will try and find a zone called "2.3.4" for the IP "1.2.3.4" (skipping the first part).

It needs to find the proper in-addr.arpa zone and also be flexible in finding zones for non-/24 subnets.

**Comment by ekohl** [comment] 2017-01-18 18:20
Given the smart-proxy now passes in-addr.arpa records, I think https://github.com/theforeman/smart_proxy_dns_route53/pull/11 should fix this issue at least for IPs. It still needs better handling in ```get_zone```, but that can be considered a duplicate of https://github.com/theforeman/smart_proxy_dns_route53/issues/10. That also is needed for IPv6 PTRs because they have a lot more dots.

**Closed as completed** 2017-02-01 12:00 UTC
Labels: bug
